import './globals.css'
// import '../css/main.css'
import Head from '@/components/common/Head'
import HeaderMark from '@/components/common/HeaderMark'
import Header from '@/components/common/Header'
import Nav from '@/components/common/Nav'
import Footer from '@/components/common/Footer'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app'
// }

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <Head />
      <body>
        <div id="wrapper">
          <HeaderMark />
          <Header />
          <Nav />
          <div id="main">{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  )
}
